In [1]:
from asyncio import start_server
from calendar import weekday
from select import KQ_NOTE_WRITE

import seaborn as sns
import matplotlib.pyplot as plt
import polars as pl
import polars.selectors as cs
import altair as alt
import plotly.express as px
import plotly.graph_objects as go
import great_tables as tg
import datetime as dt
import numpy as np
import pandas as pd

In [2]:
df_path = r'/Users/zygimantas/Downloads/archive (1)/fitness_dataset.csv'

In [3]:
df = pl.read_csv(df_path)

In [4]:
df

shape: (2_000, 11)
┌─────┬───────────┬───────────┬────────────┬───┬────────────────┬────────┬────────┬────────┐
│ age ┆ height_cm ┆ weight_kg ┆ heart_rate ┆ … ┆ activity_index ┆ smokes ┆ gender ┆ is_fit │
│ --- ┆ ---       ┆ ---       ┆ ---        ┆   ┆ ---            ┆ ---    ┆ ---    ┆ ---    │
│ i64 ┆ i64       ┆ i64       ┆ f64        ┆   ┆ f64            ┆ str    ┆ str    ┆ i64    │
╞═════╪═══════════╪═══════════╪════════════╪═══╪════════════════╪════════╪════════╪════════╡
│ 56  ┆ 152       ┆ 65        ┆ 69.6       ┆ … ┆ 3.97           ┆ no     ┆ F      ┆ 1      │
│ 69  ┆ 186       ┆ 95        ┆ 60.8       ┆ … ┆ 3.19           ┆ 0      ┆ F      ┆ 1      │
│ 46  ┆ 192       ┆ 103       ┆ 61.4       ┆ … ┆ 2.03           ┆ 0      ┆ F      ┆ 0      │
│ 32  ┆ 189       ┆ 83        ┆ 60.2       ┆ … ┆ 3.68           ┆ 0      ┆ M      ┆ 1      │
│ 60  ┆ 175       ┆ 99        ┆ 58.1       ┆ … ┆ 4.83           ┆ yes    ┆ F      ┆ 1      │
│ …   ┆ …         ┆ …         ┆ …          ┆ … ┆ …              ┆ …      ┆ …      ┆ …      │
│ 52  ┆ 173       ┆ 98        ┆ 60.7       ┆ … ┆ 3.25           ┆ 1      ┆ M      ┆ 1      │
│ 61  ┆ 186       ┆ 74        ┆ 51.4       ┆ … ┆ 3.15           ┆ no     ┆ M      ┆ 1      │
│ 77  ┆ 198       ┆ 89        ┆ 76.7       ┆ … ┆ 3.36           ┆ yes    ┆ M      ┆ 0      │
│ 62  ┆ 190       ┆ 63        ┆ 80.7       ┆ … ┆ 2.39           ┆ 1      ┆ F      ┆ 0      │
│ 51  ┆ 166       ┆ 78        ┆ 89.3       ┆ … ┆ 1.02           ┆ 1      ┆ M      ┆ 0      │
└─────┴───────────┴───────────┴────────────┴───┴────────────────┴────────┴────────┴────────┘

In [5]:
df = df.with_columns(
    cs.integer().shrink_dtype()
)

In [6]:
df.null_count()

shape: (1, 11)
┌─────┬───────────┬───────────┬────────────┬───┬────────────────┬────────┬────────┬────────┐
│ age ┆ height_cm ┆ weight_kg ┆ heart_rate ┆ … ┆ activity_index ┆ smokes ┆ gender ┆ is_fit │
│ --- ┆ ---       ┆ ---       ┆ ---        ┆   ┆ ---            ┆ ---    ┆ ---    ┆ ---    │
│ u32 ┆ u32       ┆ u32       ┆ u32        ┆   ┆ u32            ┆ u32    ┆ u32    ┆ u32    │
╞═════╪═══════════╪═══════════╪════════════╪═══╪════════════════╪════════╪════════╪════════╡
│ 0   ┆ 0         ┆ 0         ┆ 0          ┆ … ┆ 0              ┆ 0      ┆ 0      ┆ 0      │
└─────┴───────────┴───────────┴────────────┴───┴────────────────┴────────┴────────┴────────┘

In [7]:
df = df.with_columns(
    pl.col('sleep_hours').fill_null(0.0)
)

In [8]:
df.describe()

shape: (9, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬────────────────┬────────┬────────┬──────────┐
│ statistic  ┆ age       ┆ height_cm ┆ weight_kg ┆ … ┆ activity_index ┆ smokes ┆ gender ┆ is_fit   │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---            ┆ ---    ┆ ---    ┆ ---      │
│ str        ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64            ┆ str    ┆ str    ┆ f64      │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪════════════════╪════════╪════════╪══════════╡
│ count      ┆ 2000.0    ┆ 2000.0    ┆ 2000.0    ┆ … ┆ 2000.0         ┆ 2000   ┆ 2000   ┆ 2000.0   │
│ null_count ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0            ┆ 0      ┆ 0      ┆ 0.0      │
│ mean       ┆ 49.114    ┆ 174.533   ┆ 83.5405   ┆ … ┆ 2.99904        ┆ null   ┆ null   ┆ 0.3995   │
│ std        ┆ 17.926564 ┆ 14.37175  ┆ 25.852534 ┆ … ┆ 1.136383       ┆ null   ┆ null   ┆ 0.489918 │
│ min        ┆ 18.0      ┆ 150.0     ┆ 30.0      ┆ … ┆ 1.0            ┆ 0      ┆ F      ┆ 0.0      │
│ 25%        ┆ 34.0      ┆ 162.0     ┆ 64.0      ┆ … ┆ 2.04           ┆ null   ┆ null   ┆ 0.0      │
│ 50%        ┆ 49.0      ┆ 174.0     ┆ 83.0      ┆ … ┆ 2.98           ┆ null   ┆ null   ┆ 0.0      │
│ 75%        ┆ 65.0      ┆ 187.0     ┆ 102.0     ┆ … ┆ 3.95           ┆ null   ┆ null   ┆ 1.0      │
│ max        ┆ 79.0      ┆ 199.0     ┆ 250.0     ┆ … ┆ 4.99           ┆ yes    ┆ M      ┆ 1.0      │
└────────────┴───────────┴───────────┴───────────┴───┴────────────────┴────────┴────────┴──────────┘

In [9]:
X = df.select(
    cs.exclude('is_fit')
)

In [10]:
y = df.get_column(
    'is_fit'
)

In [11]:
X_numeric = df.select(
    cs.numeric()
)

X_categorical = df.select(
    cs.string()
)

In [12]:
X_categorical.select(
    pl.all().n_unique()
)

shape: (1, 2)
┌────────┬────────┐
│ smokes ┆ gender │
│ ---    ┆ ---    │
│ u32    ┆ u32    │
╞════════╪════════╡
│ 4      ┆ 2      │
└────────┴────────┘

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [14]:
column_transformer = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(
            handle_unknown='ignore', sparse_output=False, drop='first'),
        X.select(cs.string()).columns),
        ('passthrough', 'passthrough', X.select(cs.numeric()).columns)
    ]
)

In [15]:
column_transformer

ColumnTransformer(transformers=[('encoder',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['smokes', 'gender']),
                                ('passthrough', 'passthrough',
                                 ['age', 'height_cm', 'weight_kg', 'heart_rate',
                                  'blood_pressure', 'sleep_hours',
                                  'nutrition_quality', 'activity_index'])])

In [16]:
X_encoded = column_transformer.fit_transform(X)

In [17]:
feature_names = column_transformer.named_transformers_['encoder'].get_feature_names_out()

In [18]:
numeric_columns = X.select(cs.numeric()).columns

In [19]:
all_feature_names = list(feature_names) + list(numeric_columns)

In [20]:
all_feature_names

['smokes_1',
 'smokes_no',
 'smokes_yes',
 'gender_M',
 'age',
 'height_cm',
 'weight_kg',
 'heart_rate',
 'blood_pressure',
 'sleep_hours',
 'nutrition_quality',
 'activity_index']

In [21]:
X_encoded = pl.DataFrame(
    X_encoded, schema=all_feature_names
)

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
scaler = StandardScaler()

In [26]:
scaler

StandardScaler()

In [27]:
scaled_X_train = scaler.fit_transform(X_train)

In [28]:
scaled_X_test = scaler.transform(X_test)

In [29]:
scaled_X_train = pl.DataFrame(scaled_X_train, schema=X_train.columns)

In [30]:
scaled_X_test = pl.DataFrame(scaled_X_test, schema=X_test.columns)

In [32]:
pandas_df = df.to_pandas()

fig = px.histogram(pandas_df, x='is_fit', title='Distribution of is_fit', color='is_fit')
fig.show()

In [35]:
fig = px.histogram(pandas_df, x='is_fit', title='Distribution of is_fit', color='is_fit')
fig.show()

In [37]:
numerical_cols = df.select(cs.numeric().exclude('is_fit')).columns
for col in numerical_cols:
    fig = px.box(pandas_df, x='is_fit', y=col, title=f'Distribution of {col} by Fitness Level', color='is_fit')
    fig.show()

In [39]:
from sklearn.linear_model import LinearRegression

In [42]:
liner_model = LinearRegression(n_jobs=-1)

In [43]:
liner_model.fit(scaled_X_train, y_train)

LinearRegression(n_jobs=-1)

In [44]:
predictions = liner_model.predict(X_test)

In [45]:
predictions

array([ -4.81280832,  -4.00579917,  -3.39591619,  -6.11168294,
        -7.02263272,  -7.42419073,  -2.26885083,  -7.54483527,
        -1.84934272,  -3.0709085 ,  -6.92333381,  -3.90020375,
        -4.4553089 ,  -3.95944336,  -7.87538046,  -1.79204242,
        -3.87670633,  -6.2254521 ,  -6.14540645,  -7.1613819 ,
        -1.08051359,  -6.10486967,  -2.79400515,  -8.97959568,
        -7.55155483,  -3.28769137,  -6.61579983,  -3.33578108,
        -5.61237781,  -3.03656137,  -0.58269226,  -3.26007123,
        -1.80741541,  -7.6080458 ,  -6.6478141 ,  -4.92605836,
        -3.47566445,  -6.67272537,  -0.98067515,  -4.62294453,
        -7.98209391,  -3.133931  ,  -2.91930814,  -6.26836535,
        -8.30749299,  -3.37801033,  -2.96326837,  -1.55139298,
        -7.3019033 ,  -2.14797645,  -5.47496425,  -6.03278254,
        -1.48602688,  -6.68448997,  -6.79082636,  -8.34894163,
        -2.65300767,  -7.306009  ,  -7.45112373,  -6.32587637,
        -7.82929179,  -4.21113474,  -8.03166228,  -3.93047062,
        -3.70456753,  -0.88913835,  -7.42325216,  -4.41767828,
        -7.55600496,  -3.94949989,  -4.86797521,  -4.47533599,
        -4.81904349,  -9.22054048,  -3.78037349,  -3.24016356,
        -6.72101004,  -1.92908344,  -8.01035926,  -7.76795687,
        -4.36971075,  -3.10380011,  -3.79259797,  -4.01413572,
        -2.28347171,  -1.99548825,  -2.36089748,  -9.4584552 ,
        -3.23264483,  -5.74534045,  -5.53209998,  -4.22800716,
        -3.24485179,  -6.27844792,  -7.06250767,  -2.78225277,
        -5.17881631,  -2.25708303,  -2.62502929,  -5.20909267,
        -7.78122188,  -5.54890845,  -8.25179139,  -3.23035627,
        -5.53297811,  -6.26724463,  -3.48977067,  -6.26308735,
        -2.90435472,  -3.68670848,  -8.30102804,  -3.50935415,
        -2.83285   ,  -2.68330478,  -4.30480813,  -3.58927667,
        -6.65924983,  -3.9510441 ,  -5.25956261,  -7.09973968,
        -2.47697582,  -3.64056017,  -5.53557362,  -5.07576229,
        -4.34184045,  -6.5399598 ,  -6.75380352,  -7.58265104,
        -7.67737932,   0.21247473,  -3.75191745,  -8.48380211,
        -7.01249202,  -5.29016573,  -8.27516921,  -2.04523535,
        -6.75411209,  -6.87209697,  -4.07442745,  -5.60270261,
        -8.02661393,  -7.88309831,  -6.25848073,  -2.10001037,
        -5.91916455,  -3.46585005,  -4.76398832,  -1.31864894,
        -3.60230272,  -4.70927398,  -1.70556684,  -6.55067802,
        -4.25465377,  -7.37498379,  -7.99001376,  -2.54038143,
        -4.69663041,  -0.16876442,  -3.90349771,  -3.05361462,
       -10.75157315,  -6.54165867,  -4.40833441,  -2.20268681,
        -1.84147428,  -3.10113165,  -3.08745772,  -3.56660155,
        -2.91094949,  -4.68733027,  -5.87269054,  -1.48725101,
        -4.30480786,  -2.4989708 ,  -9.10052909,  -0.65237653,
        -3.00003166,  -5.46501321,  -6.73379454,  -5.72626253,
        -5.20202203,  -3.62452539,  -5.43701102,  -5.01381037,
        -4.76086485,  -7.62845572,  -2.0116376 ,  -2.85583562,
        -6.15127163,  -4.65821597,  -2.09063583,  -6.78492822,
        -5.68740347,  -5.69224397,  -7.4424244 ,  -2.98162314,
        -3.5565654 ,  -4.39023741,  -5.17543006,  -1.92308362,
        -2.43406049,  -1.24456458,  -3.96076836,  -3.70043518,
        -3.71407179,  -5.38281722,  -4.00476937,  -3.8936193 ,
        -7.68576174,  -3.1150139 ,  -5.27653257,  -4.99078305,
        -5.58770351,  -4.11507058,  -4.86806663,  -3.34179876,
        -4.02370224,  -5.48656286,  -3.207675  ,  -3.64817057,
        -6.93196053,  -6.12374554,  -3.63913097,  -6.61065167,
        -5.29270129,  -2.21238465,  -4.01651   ,  -3.06676725,
        -3.08359598,  -5.48346451,  -5.14113372,  -6.55817834,
        -6.25139462,  -6.68885508,  -5.38307778,  -6.46142506,
        -6.01541775,  -4.74433942,  -4.72966818,  -5.43556706,
        -2.2818237 ,  -1.40880558,  -4.80522262,  -6.16736157,
        -2.10395542,  -2.17472973,  -2.32598422,  -0.74634364,
        -1.90090301,  -2.50149776,  -1.93496356,  -3.60456995,
        -7.26324599,  -6.53463061,  -5.46703703,  -5.00710035,
        -2.93535661,  -5.9158097 ,  -1.21596002,  -5.66938076,
        -6.30272206,  -5.76827447,  -6.43287544,  -3.04835774,
        -4.20529812,  -3.71606451,  -3.64757301,  -8.16664945,
        -5.03853021,  -2.6730338 ,  -1.69367578,  -3.38762588,
        -5.73835188,  -0.68858063,  -3.61857898,  -1.87452161,
        -4.92750039,  -7.07941088,  -6.76875894,  -6.13671812,
        -5.86874548,  -4.97734896,  -2.11741836,  -7.05870512,
        -5.90431046,  -0.54942641,  -2.38962544,  -1.85248165,
        -3.55517921,  -2.63107048,  -5.56087642,  -4.79183451,
        -5.72894384,  -5.96409707,  -7.0993262 ,  -2.41488065,
        -7.34460976,  -5.0708795 ,  -5.90399078,  -4.33560303,
        -6.0855758 ,  -3.31735309,  -5.63047157,  -8.4644508 ,
        -6.42905184,  -2.66836788,  -1.87475462,  -5.23698151,
        -2.10671631,  -2.89855044,  -4.19179738,  -7.15935175,
        -7.14306303,  -6.67364558,  -4.27928845,  -4.58862732,
        -5.74303122,  -2.55045562,  -3.90633094,  -8.13501312,
        -2.2063229 ,  -5.29956205,  -3.82916899,  -3.02394957,
        -2.26592173,  -8.02490424,  -5.71708467,  -7.37859736,
        -3.21477716,  -2.81291174,  -5.49899586,  -5.31800424,
        -2.30812124,  -7.76923752,  -5.36703243,  -4.29062966,
        -5.85099235,  -1.35702723,  -3.33802244,  -1.31073846,
        -2.43331572,  -3.24415987,  -5.7251777 ,  -2.96527236,
        -3.86745522,  -4.56461091,  -6.82195677,  -3.08434559,
        -2.49988945,  -3.49575958,  -6.47118353,  -5.13992828,
        -2.18373566,  -9.32989131,  -6.98801167,  -7.38394712,
        -5.83447481,  -8.27924634,  -5.69619886,  -7.04764694,
        -4.69855407,  -2.2592745 ,  -2.21634619,  -3.89704367,
        -4.06200725,  -4.03078048,  -3.96050891,  -6.28436402,
        -7.3350812 ,  -6.00317074,  -6.61122043,  -5.52396982,
        -8.22456695,  -4.03719599,  -2.98169319,  -5.73112339,
        -6.4469854 ,  -3.46791563,  -4.64901307,  -3.81801141,
        -4.90057245,  -6.35685915,  -5.07346809,  -3.62116725,
        -2.2214334 ,  -3.43354848,  -3.92100404,  -3.9302979 ,
        -6.88872932,  -2.05999213,  -2.41770824,  -2.25102765,
        -7.93085246,  -6.88881406,  -3.20914123,  -3.69462223,
        -8.15168938,  -3.93398171,  -7.3603492 ,  -3.365937  ])

In [46]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_absolute_percentage_error

In [49]:
pl.DataFrame({
    'actual': y_test,
    'predicted': predictions,
    'error': y_test - predictions,
    'error_percent': (y_test - predictions) / y_test * 100,
    'error_abs_percent': np.abs(y_test - predictions) / y_test * 100,
    'error_squared': (y_test - predictions) ** 2,
})

shape: (400, 6)
┌────────┬───────────┬──────────┬───────────────┬───────────────────┬───────────────┐
│ actual ┆ predicted ┆ error    ┆ error_percent ┆ error_abs_percent ┆ error_squared │
│ ---    ┆ ---       ┆ ---      ┆ ---           ┆ ---               ┆ ---           │
│ i8     ┆ f64       ┆ f64      ┆ f64           ┆ f64               ┆ f64           │
╞════════╪═══════════╪══════════╪═══════════════╪═══════════════════╪═══════════════╡
│ 1      ┆ -4.812808 ┆ 5.812808 ┆ 581.280832    ┆ 581.280832        ┆ 33.788741     │
│ 1      ┆ -4.005799 ┆ 5.005799 ┆ 500.579917    ┆ 500.579917        ┆ 25.058025     │
│ 1      ┆ -3.395916 ┆ 4.395916 ┆ 439.591619    ┆ 439.591619        ┆ 19.324079     │
│ 1      ┆ -6.111683 ┆ 7.111683 ┆ 711.168294    ┆ 711.168294        ┆ 50.576034     │
│ 0      ┆ -7.022633 ┆ 7.022633 ┆ inf           ┆ inf               ┆ 49.31737      │
│ …      ┆ …         ┆ …        ┆ …             ┆ …                 ┆ …             │
│ 0      ┆ -3.694622 ┆ 3.694622 ┆ inf           ┆ inf               ┆ 13.650233     │
│ 0      ┆ -8.151689 ┆ 8.151689 ┆ inf           ┆ inf               ┆ 66.45004      │
│ 0      ┆ -3.933982 ┆ 3.933982 ┆ inf           ┆ inf               ┆ 15.476212     │
│ 0      ┆ -7.360349 ┆ 7.360349 ┆ inf           ┆ inf               ┆ 54.17474      │
│ 0      ┆ -3.365937 ┆ 3.365937 ┆ inf           ┆ inf               ┆ 11.329532     │
└────────┴───────────┴──────────┴───────────────┴───────────────────┴───────────────┘

In [54]:
MSE = mean_squared_error(y_test, predictions)
RMSE = np.sqrt(MSE)
MAE = mean_absolute_error(y_test, predictions)
MAE = mean_absolute_percentage_error(y_test, predictions)
R2 = r2_score(y_test, predictions)

In [55]:
f'MSE {MSE:.2f}, RMSE {RMSE:.2f}, MAE {MAE:.2f}'

'MSE 29.85, RMSE 5.46, MAE 14184009746659248.00'

In [67]:
results = pl.DataFrame({
    'Error': [MSE, RMSE, MAE, MAE, R2],
    'Metric': ['MSE', 'RMSE', 'MAE', 'MAPE', 'R2']
})

In [57]:
from sklearn.model_selection import GridSearchCV

In [58]:
liner_reg_parm_grid = {
    'fit_intercept': [True, False],
    'positive': [True, False],
    'copy_X': [True, False],
    'n_jobs': [-1]
}

In [59]:
grid_search = GridSearchCV(
    estimator=LinearRegression(),
    param_grid=liner_reg_parm_grid,
    cv=5,
    verbose=1,
    n_jobs=-1
)

In [60]:
grid_search.fit(scaled_X_train, y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(cv=5, estimator=LinearRegression(), n_jobs=-1,
             param_grid={'copy_X': [True, False],
                         'fit_intercept': [True, False], 'n_jobs': [-1],
                         'positive': [True, False]},
             verbose=1)

In [61]:
predictions = grid_search.predict(X_test)

In [62]:
pl.DataFrame({
    'actual': y_test,
    'predicted': grid_search.predict(X_test),
    'error': (grid_search.predict(X_test) - y_test),
    'error_percent': (grid_search.predict(X_test) - y_test) / y_test,
})

shape: (400, 4)
┌────────┬───────────┬───────────┬───────────────┐
│ actual ┆ predicted ┆ error     ┆ error_percent │
│ ---    ┆ ---       ┆ ---       ┆ ---           │
│ i8     ┆ f64       ┆ f64       ┆ f64           │
╞════════╪═══════════╪═══════════╪═══════════════╡
│ 1      ┆ -4.812808 ┆ -5.812808 ┆ -5.812808     │
│ 1      ┆ -4.005799 ┆ -5.005799 ┆ -5.005799     │
│ 1      ┆ -3.395916 ┆ -4.395916 ┆ -4.395916     │
│ 1      ┆ -6.111683 ┆ -7.111683 ┆ -7.111683     │
│ 0      ┆ -7.022633 ┆ -7.022633 ┆ -inf          │
│ …      ┆ …         ┆ …         ┆ …             │
│ 0      ┆ -3.694622 ┆ -3.694622 ┆ -inf          │
│ 0      ┆ -8.151689 ┆ -8.151689 ┆ -inf          │
│ 0      ┆ -3.933982 ┆ -3.933982 ┆ -inf          │
│ 0      ┆ -7.360349 ┆ -7.360349 ┆ -inf          │
│ 0      ┆ -3.365937 ┆ -3.365937 ┆ -inf          │
└────────┴───────────┴───────────┴───────────────┘

In [63]:
MSE = mean_squared_error(y_test, grid_search.predict(X_test))
RMSE = np.sqrt(MSE)
MAE = mean_absolute_error(y_test, grid_search.predict(X_test))
r2 = r2_score(y_test, grid_search.predict(X_test))
percent_error = mean_absolute_percentage_error(y_test, grid_search.predict(X_test))

In [64]:
liner_reg_cv_values = [MSE, RMSE, r2, MAE, percent_error]

In [68]:
results = results.with_columns(pl.Series(
    name='Linera Regression CV', values=liner_reg_cv_values
))

In [69]:
results

shape: (5, 3)
┌─────────────┬────────┬──────────────────────┐
│ Error       ┆ Metric ┆ Linera Regression CV │
│ ---         ┆ ---    ┆ ---                  │
│ f64         ┆ str    ┆ f64                  │
╞═════════════╪════════╪══════════════════════╡
│ 29.852826   ┆ MSE    ┆ 29.852826            │
│ 5.463774    ┆ RMSE   ┆ 5.463774             │
│ 5.118945    ┆ MAE    ┆ -122.183808          │
│ 5.118945    ┆ MAPE   ┆ 5.118945             │
│ -122.183808 ┆ R2     ┆ 1.4184e16            │
└─────────────┴────────┴──────────────────────┘

In [71]:
from sklearn.svm import SVR

In [72]:
svm = SVR()

In [99]:
svm_cv_parms = {
    'kernel': ['poly', 'linear', 'rbf', 'sigmoid'],
    'degree': [1, 2, 3, 4],
    'gamma': ['auto'],
    'epsilon': [0.01, 0.1, 0.5, 1]
}

In [100]:
svr_grid_search = GridSearchCV(
    estimator=svm,
    param_grid=svm_cv_parms,
    cv=5,
    verbose=1,
    n_jobs=-1
)

In [101]:
svr_grid_search.fit(scaled_X_train, y_train)

Fitting 7 folds for each of 64 candidates, totalling 448 fits

GridSearchCV(cv=7, estimator=SVR(), n_jobs=-1,
             param_grid={'degree': [1, 2, 3, 4], 'epsilon': [0.01, 0.1, 0.5, 1],
                         'gamma': ['auto'],
                         'kernel': ['poly', 'linear', 'rbf', 'sigmoid']},
             verbose=1)

In [102]:
svr_grid_search.predict(X_test)

array([0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847,
       0.24572847, 0.24572847, 0.24572847, 0.24572847, 0.24572847])

In [103]:
svr_grid_search.best_params_

{'degree': 1, 'epsilon': 0.01, 'gamma': 'auto', 'kernel': 'rbf'}

In [104]:
MSE = mean_squared_error(y_test, svr_grid_search.predict(X_test))
RMSE = np.sqrt(MSE)
MAE = mean_absolute_error(y_test, svr_grid_search.predict(X_test))
r2 = r2_score(y_test, svr_grid_search.predict(X_test))
percent_error = mean_absolute_percentage_error(y_test, svr_grid_search.predict(X_test))

In [105]:
result = results.with_columns(
    pl.Series(name='SVR CV', values=[MSE, RMSE, r2, MAE, percent_error])
)

In [106]:
print(result)

shape: (5, 4)
┌─────────────┬────────┬──────────────────────┬───────────┐
│ Error       ┆ Metric ┆ Linera Regression CV ┆ SVR CV    │
│ ---         ┆ ---    ┆ ---                  ┆ ---       │
│ f64         ┆ str    ┆ f64                  ┆ f64       │
╞═════════════╪════════╪══════════════════════╪═══════════╡
│ 29.852826   ┆ MSE    ┆ 29.852826            ┆ 0.270156  │
│ 5.463774    ┆ RMSE   ┆ 5.463774             ┆ 0.519766  │
│ 5.118945    ┆ MAE    ┆ -122.183808          ┆ -0.114766 │
│ 5.118945    ┆ MAPE   ┆ 5.118945             ┆ 0.455502  │
│ -122.183808 ┆ R2     ┆ 1.4184e16            ┆ 6.5016e14 │
└─────────────┴────────┴──────────────────────┴───────────┘

In [107]:
from sklearn.neighbors import KNeighborsClassifier

In [108]:
knn_cv_parms = {
    'n_neighbors': [1, 2, 3, 4 ,5],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size': [30, 40, 50],
    'p': [1, 2],
    'metric': ['minkowski'],
    'n_jobs': [-1]
}

In [109]:
knn_grid_search = GridSearchCV(
    estimator=KNeighborsClassifier(),
    param_grid=knn_cv_parms,
    cv=5,
    verbose=1,
    n_jobs=-1
)

In [110]:
knn_grid_search.fit(scaled_X_train, y_train)

Fitting 5 folds for each of 240 candidates, totalling 1200 fits

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [30, 40, 50], 'metric': ['minkowski'],
                         'n_jobs': [-1], 'n_neighbors': [1, 2, 3, 4, 5],
                         'p': [1, 2], 'weights': ['uniform', 'distance']},
             verbose=1)

In [112]:
knn_grid_search.predict(X_test)

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1], dtype=int8)

In [113]:
knn_grid_search.best_params_

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'n_jobs': -1,
 'n_neighbors': 5,
 'p': 1,
 'weights': 'uniform'}

In [114]:
MSE = mean_squared_error(y_test, knn_grid_search.predict(X_test))
RMSE = np.sqrt(MSE)
MAE = mean_absolute_error(y_test, knn_grid_search.predict(X_test))
r2 = r2_score(y_test, knn_grid_search.predict(X_test))
percent_error = mean_absolute_percentage_error(y_test, knn_grid_search.predict(X_test))

In [115]:
knn_grid_values = [MSE, RMSE, r2, MAE, percent_error]

In [117]:
results = result.with_columns(
    pl.Series(name='KNN CV', values=knn_grid_values)
)

In [118]:
from sklearn.tree import DecisionTreeClassifier

In [125]:
desition_tree_params = {
    'criterion': ['gini', 'entropy'],
    'splitter': ['best', 'random'],
    'max_depth': [1, 2, 3, 4, 5],
    'min_samples_split': [2, 3, 4, 5],
    'min_samples_leaf': [1, 2, 3, 4, 5],
    'min_weight_fraction_leaf': [0.0, 0.1, 0.2, 0.3, 0.4, 0.5],
    'max_features': [None, 'sqrt', 'log2'],
    'random_state': [42]
}

In [126]:
desition_tree_grid_search = GridSearchCV(
    estimator=DecisionTreeClassifier(),
    param_grid=desition_tree_params,
    cv=5,
    verbose=1,
    n_jobs=-1
)

In [127]:
desition_tree_grid_search.fit(scaled_X_train, y_train)

Fitting 5 folds for each of 7200 candidates, totalling 36000 fits

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4, 5],
                         'max_features': [None, 'sqrt', 'log2'],
                         'min_samples_leaf': [1, 2, 3, 4, 5],
                         'min_samples_split': [2, 3, 4, 5],
                         'min_weight_fraction_leaf': [0.0, 0.1, 0.2, 0.3, 0.4,
                                                      0.5],
                         'random_state': [42], 'splitter': ['best', 'random']},
             verbose=1)

In [128]:
desition_tree_grid_search.best_params_

{'criterion': 'gini',
 'max_depth': 5,
 'max_features': None,
 'min_samples_leaf': 3,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': 42,
 'splitter': 'best'}

In [129]:
predictions = desition_tree_grid_search.predict(X_test)

In [131]:
MSE = mean_squared_error(y_test, predictions)
RMSE = np.sqrt(MSE)
MAE = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)
percent_error = mean_absolute_percentage_error(y_test, predictions)

In [132]:
desition_tree_grid_search_values = [MSE, RMSE, r2, MAE, percent_error]

In [134]:
results = results.with_columns(
    pl.Series(name='Desition Tree CV', values=desition_tree_grid_search_values)
)

In [135]:
from sklearn.ensemble import RandomForestClassifier

In [158]:
rfc_cv_params = {
    'n_estimators': [25, 100],
    'max_depth': [3, 5, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt', 'log2', None],
    'bootstrap': [True],
    'random_state': [42],
    'n_jobs': [-1]
}

In [159]:
rfc_grid_search = GridSearchCV(
    estimator=RandomForestClassifier(),
    param_grid=rfc_cv_params,
    cv=5,
    verbose=1,
)

In [160]:
rfc_grid_search.fit(scaled_X_train, y_train)

Fitting 5 folds for each of 144 candidates, totalling 720 fits

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'bootstrap': [True], 'max_depth': [3, 5, None],
                         'max_features': ['sqrt', 'log2', None],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [25, 50, 75, 100], 'n_jobs': [-1],
                         'random_state': [42]},
             verbose=1)

In [161]:
rfc_grid_search.best_params_

{'bootstrap': True,
 'max_depth': None,
 'max_features': 'sqrt',
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 100,
 'n_jobs': -1,
 'random_state': 42}

In [162]:
predictions = rfc_grid_search.predict(X_test)

In [163]:
MSE = mean_squared_error(y_test, predictions)
RMSE = np.sqrt(MSE)
MAE = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)
percent_error = mean_absolute_percentage_error(y_test, predictions)

In [165]:
results = results.with_columns(
    pl.Series(name='Random Forest CV', values=[MSE, RMSE, r2, MAE, percent_error])
)

In [166]:
from sklearn.naive_bayes import GaussianNB

In [174]:
gaussian_nb_cv_parms = {
    'var_smoothing': [1e-09, 1e-10, 1e-11],
    'priors': [None],
}

In [175]:
gaussian_nb_grid_search = GridSearchCV(
    estimator=GaussianNB(),
    param_grid=gaussian_nb_cv_parms,
    cv=5,
    verbose=1,
)

In [176]:
gaussian_nb_grid_search.fit(scaled_X_train, y_train)

Fitting 5 folds for each of 3 candidates, totalling 15 fits

GridSearchCV(cv=5, estimator=GaussianNB(),
             param_grid={'priors': [None],
                         'var_smoothing': [1e-09, 1e-10, 1e-11]},
             verbose=1)

In [182]:
predictions = gaussian_nb_grid_search.predict(X_test)
predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int8)

In [179]:
MSE = mean_squared_error(y_test, predictions)
RMSE = np.sqrt(MSE)
MAE = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)
percent_error = mean_absolute_percentage_error(y_test, predictions)

In [180]:
results = results.with_columns(
    pl.Series(name='Gaussian NB CV', values=[MSE, RMSE, r2, MAE, percent_error])
)

In [181]:
results

shape: (5, 8)
┌─────────────┬────────┬────────────┬───────────┬───────────┬────────────┬────────────┬────────────┐
│ Error       ┆ Metric ┆ Linera     ┆ SVR CV    ┆ KNN CV    ┆ Desition   ┆ Random     ┆ Gaussian   │
│ ---         ┆ ---    ┆ Regression ┆ ---       ┆ ---       ┆ Tree CV    ┆ Forest CV  ┆ NB CV      │
│ f64         ┆ str    ┆ CV         ┆ f64       ┆ f64       ┆ ---        ┆ ---        ┆ ---        │
│             ┆        ┆ ---        ┆           ┆           ┆ f64        ┆ f64        ┆ f64        │
│             ┆        ┆ f64        ┆           ┆           ┆            ┆            ┆            │
╞═════════════╪════════╪════════════╪═══════════╪═══════════╪════════════╪════════════╪════════════╡
│ 29.852826   ┆ MSE    ┆ 29.852826  ┆ 0.270156  ┆ 0.5775    ┆ 0.57       ┆ 0.4925     ┆ 0.4125     │
│ 5.463774    ┆ RMSE   ┆ 5.463774   ┆ 0.519766  ┆ 0.759934  ┆ 0.754983   ┆ 0.701783   ┆ 0.642262   │
│ 5.118945    ┆ MAE    ┆ -122.18380 ┆ -0.114766 ┆ -1.382979 ┆ -1.352031  ┆ -1.032237  ┆ -0.702128  │
│             ┆        ┆ 8          ┆           ┆           ┆            ┆            ┆            │
│ 5.118945    ┆ MAPE   ┆ 5.118945   ┆ 0.455502  ┆ 0.5775    ┆ 0.57       ┆ 0.4925     ┆ 0.4125     │
│ -122.183808 ┆ R2     ┆ 1.4184e16  ┆ 6.5016e14 ┆ 2.4545e15 ┆ 2.5671e15  ┆ 2.0266e15  ┆ 0.4125     │
└─────────────┴────────┴────────────┴───────────┴───────────┴────────────┴────────────┴────────────┘

In [183]:
from sklearn.ensemble import GradientBoostingClassifier

Looking at the selected cell, I need to remove all the comments from the `gbc_cv_params` dictionary definition.

In [192]:
gbc_cv_params = {
    'n_estimators': [50, 100],
    'max_depth': [3, 5, None],
    'learning_rate': [0.01, 0.1],
    'subsample': [0.8, 1.0],
    'loss': ['log_loss'],
    'min_samples_split': [2, 10],
    'min_samples_leaf': [1, 4],
    'max_features': ['sqrt'],
    'criterion': ['friedman_mse']
}

In [193]:
gbc_grid_search = GridSearchCV(
    estimator=GradientBoostingClassifier(),
    param_grid=gbc_cv_params,
    cv=5,
    verbose=1,
)

In [194]:
gbc_grid_search.fit(scaled_X_train, y_train)

Fitting 5 folds for each of 96 candidates, totalling 480 fits

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(),
             param_grid={'criterion': ['friedman_mse'],
                         'learning_rate': [0.01, 0.1], 'loss': ['log_loss'],
                         'max_depth': [3, 5, None], 'max_features': ['sqrt'],
                         'min_samples_leaf': [1, 4],
                         'min_samples_split': [2, 10],
                         'n_estimators': [50, 100], 'subsample': [0.8, 1.0]},
             verbose=1)

In [195]:
predictions = gbc_grid_search.predict(X_test)

In [196]:
predictions

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1], dtype=int8)

In [197]:
MSE = mean_squared_error(y_test, predictions)
RMSE = np.sqrt(MSE)
MAE = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)
percent_error = mean_absolute_percentage_error(y_test, predictions)

In [199]:
results = results.with_columns(
    pl.Series(name='Gradient Boosting CV', values=[MSE, RMSE, r2, MAE, percent_error])
)

In [202]:
results

shape: (5, 9)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Error      ┆ Metric ┆ Linera     ┆ SVR CV    ┆ … ┆ Desition  ┆ Random    ┆ Gaussian  ┆ Gradient  │
│ ---        ┆ ---    ┆ Regression ┆ ---       ┆   ┆ Tree CV   ┆ Forest CV ┆ NB CV     ┆ Boosting  │
│ f64        ┆ str    ┆ CV         ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ CV        │
│            ┆        ┆ ---        ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---       │
│            ┆        ┆ f64        ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 29.852826  ┆ MSE    ┆ 29.852826  ┆ 0.270156  ┆ … ┆ 0.57      ┆ 0.4925    ┆ 0.4125    ┆ 0.565     │
│ 5.463774   ┆ RMSE   ┆ 5.463774   ┆ 0.519766  ┆ … ┆ 0.754983  ┆ 0.701783  ┆ 0.642262  ┆ 0.751665  │
│ 5.118945   ┆ MAE    ┆ -122.18380 ┆ -0.114766 ┆ … ┆ -1.352031 ┆ -1.032237 ┆ -0.702128 ┆ -1.331399 │
│            ┆        ┆ 8          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 5.118945   ┆ MAPE   ┆ 5.118945   ┆ 0.455502  ┆ … ┆ 0.57      ┆ 0.4925    ┆ 0.4125    ┆ 0.565     │
│ -122.18380 ┆ R2     ┆ 1.4184e16  ┆ 6.5016e14 ┆ … ┆ 2.5671e15 ┆ 2.0266e15 ┆ 0.4125    ┆ 2.5445e15 │
│ 8          ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘