# https://www.kaggle.com/datasets/umuttuygurr/e-commerce-fraud-detection-dataset

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import polars as pl
import polars.selectors as cs
import altair as alt
import plotly.express as px
import plotly.graph_objects as go
import great_tables as tg
import datetime as dt
import numpy as np
import pandas as pd
from imblearn.over_sampling import SMOTE

In [2]:
df_path = r'/Users/zygimantas/Documents/Data_sets/transactions.csv'

In [3]:
df = pl.read_csv(df_path, infer_schema_length=10_000)

In [4]:
df.null_count()

shape: (1, 17)
┌────────────┬─────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ transactio ┆ user_id ┆ account_ag ┆ total_tra ┆ … ┆ three_ds_ ┆ transacti ┆ shipping_ ┆ is_fraud │
│ n_id       ┆ ---     ┆ e_days     ┆ nsactions ┆   ┆ flag      ┆ on_time   ┆ distance_ ┆ ---      │
│ ---        ┆ u32     ┆ ---        ┆ _user     ┆   ┆ ---       ┆ ---       ┆ km        ┆ u32      │
│ u32        ┆         ┆ u32        ┆ ---       ┆   ┆ u32       ┆ u32       ┆ ---       ┆          │
│            ┆         ┆            ┆ u32       ┆   ┆           ┆           ┆ u32       ┆          │
╞════════════╪═════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0          ┆ 0       ┆ 0          ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
└────────────┴─────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
df.select(
    df.select(
        cs.string().n_unique()
    )
)

shape: (1, 5)
┌─────────┬─────────────┬─────────┬───────────────────┬──────────────────┐
│ country ┆ bin_country ┆ channel ┆ merchant_category ┆ transaction_time │
│ ---     ┆ ---         ┆ ---     ┆ ---               ┆ ---              │
│ u32     ┆ u32         ┆ u32     ┆ u32               ┆ u32              │
╞═════════╪═════════════╪═════════╪═══════════════════╪══════════════════╡
│ 10      ┆ 10          ┆ 2       ┆ 5                 ┆ 297975           │
└─────────┴─────────────┴─────────┴───────────────────┴──────────────────┘

In [6]:
df.collect_schema()

Schema([('transaction_id', Int64),
        ('user_id', Int64),
        ('account_age_days', Int64),
        ('total_transactions_user', Int64),
        ('avg_amount_user', Float64),
        ('amount', Float64),
        ('country', String),
        ('bin_country', String),
        ('channel', String),
        ('merchant_category', String),
        ('promo_used', Int64),
        ('avs_match', Int64),
        ('cvv_result', Int64),
        ('three_ds_flag', Int64),
        ('transaction_time', String),
        ('shipping_distance_km', Float64),
        ('is_fraud', Int64)])

In [7]:
df = df.with_columns(
    pl.col('transaction_time').str.strptime(pl.Datetime, '%Y-%m-%dT%H:%M:%SZ')
)

In [8]:
df.select(
    cs.all().shrink_dtype()
).estimated_size('mb')

13.834456443786621

In [9]:
df.select(
    cs.all()
).estimated_size('mb')

33.8412561416626

In [10]:
df = df.select(
    cs.all().shrink_dtype()
)

In [11]:
df.select(
    cs.exclude(['transaction_id'])
)

shape: (299_695, 16)
┌─────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ user_id ┆ account_ag ┆ total_tran ┆ avg_amoun ┆ … ┆ three_ds_ ┆ transacti ┆ shipping_ ┆ is_fraud │
│ ---     ┆ e_days     ┆ sactions_u ┆ t_user    ┆   ┆ flag      ┆ on_time   ┆ distance_ ┆ ---      │
│ i16     ┆ ---        ┆ ser        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ km        ┆ i8       │
│         ┆ i16        ┆ ---        ┆ f32       ┆   ┆ i8        ┆ datetime[ ┆ ---       ┆          │
│         ┆            ┆ i8         ┆           ┆   ┆           ┆ μs]       ┆ f32       ┆          │
╞═════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1       ┆ 141        ┆ 47         ┆ 147.92999 ┆ … ┆ 1         ┆ 2024-01-0 ┆ 370.95001 ┆ 0        │
│         ┆            ┆            ┆ 3         ┆   ┆           ┆ 6         ┆ 2         ┆          │
│         ┆            ┆            ┆           ┆   ┆           ┆ 04:09:39  ┆           ┆          │
│ 1       ┆ 141        ┆ 47         ┆ 147.92999 ┆ … ┆ 0         ┆ 2024-01-0 ┆ 149.61999 ┆ 0        │
│         ┆            ┆            ┆ 3         ┆   ┆           ┆ 9         ┆ 5         ┆          │
│         ┆            ┆            ┆           ┆   ┆           ┆ 20:13:47  ┆           ┆          │
│ 1       ┆ 141        ┆ 47         ┆ 147.92999 ┆ … ┆ 1         ┆ 2024-01-1 ┆ 164.08000 ┆ 0        │
│         ┆            ┆            ┆ 3         ┆   ┆           ┆ 2         ┆ 2         ┆          │
│         ┆            ┆            ┆           ┆   ┆           ┆ 06:20:11  ┆           ┆          │
│ 1       ┆ 141        ┆ 47         ┆ 147.92999 ┆ … ┆ 1         ┆ 2024-01-1 ┆ 397.39999 ┆ 0        │
│         ┆            ┆            ┆ 3         ┆   ┆           ┆ 5         ┆ 4         ┆          │
│         ┆            ┆            ┆           ┆   ┆           ┆ 17:00:04  ┆           ┆          │
│ 1       ┆ 141        ┆ 47         ┆ 147.92999 ┆ … ┆ 1         ┆ 2024-01-1 ┆ 935.28002 ┆ 0        │
│         ┆            ┆            ┆ 3         ┆   ┆           ┆ 7         ┆ 9         ┆          │
│         ┆            ┆            ┆           ┆   ┆           ┆ 01:27:31  ┆           ┆          │
│ …       ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 6000    ┆ 996        ┆ 45         ┆ 27.93     ┆ … ┆ 0         ┆ 2024-09-2 ┆ 218.55000 ┆ 0        │
│         ┆            ┆            ┆           ┆   ┆           ┆ 9         ┆ 3         ┆          │
│         ┆            ┆            ┆           ┆   ┆           ┆ 04:40:54  ┆           ┆          │
│ 6000    ┆ 996        ┆ 45         ┆ 27.93     ┆ … ┆ 1         ┆ 2024-10-0 ┆ 185.55000 ┆ 0        │
│         ┆            ┆            ┆           ┆   ┆           ┆ 3         ┆ 3         ┆          │
│         ┆            ┆            ┆           ┆   ┆           ┆ 08:49:02  ┆           ┆          │
│ 6000    ┆ 996        ┆ 45         ┆ 27.93     ┆ … ┆ 1         ┆ 2024-10-2 ┆ 33.5      ┆ 0        │
│         ┆            ┆            ┆           ┆   ┆           ┆ 6         ┆           ┆          │
│         ┆            ┆            ┆           ┆   ┆           ┆ 07:40:38  ┆           ┆          │
│ 6000    ┆ 996        ┆ 45         ┆ 27.93     ┆ … ┆ 0         ┆ 2024-10-2 ┆ 71.75     ┆ 0        │
│         ┆            ┆            ┆           ┆   ┆           ┆ 7         ┆           ┆          │
│         ┆            ┆            ┆           ┆   ┆           ┆ 09:31:56  ┆           ┆          │
│ 6000    ┆ 996        ┆ 45         ┆ 27.93     ┆ … ┆ 1         ┆ 2024-10-3 ┆ 355.82998 ┆ 0        │
│         ┆            ┆            ┆           ┆   ┆           ┆ 0         ┆ 7         ┆          │
│         ┆            ┆            ┆           ┆   ┆           ┆ 11:10:23  ┆           ┆          │
└─────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
df = df.with_columns(
    pl.col('transaction_time').dt.year().alias('year'),
    pl.col('transaction_time').dt.month().alias('month'),
    pl.col('transaction_time').dt.day().alias('day'),
    pl.col('transaction_time').dt.hour().alias('hour'),
    pl.col('transaction_time').dt.minute().alias('minute'),
    pl.col('transaction_time').dt.second().alias('second'),
).select(
    cs.all().shrink_dtype()
)

In [13]:
df.estimated_size('mb')

15.835136413574219

In [14]:
df.select(
    cs.exclude(['transaction_id', 'transaction_time'])
).estimated_size('mb')

12.405399322509766

In [15]:
df = df.select(
    cs.exclude(['transaction_id', 'transaction_time'])
)

In [16]:
df = df.with_columns(
    pl.col('is_fraud').cast(pl.Boolean),
)

In [17]:
df.estimated_size('mb')

12.15536880493164

In [18]:
df

shape: (299_695, 21)
┌─────────┬─────────────────┬─────────────────┬─────────────────┬───┬─────┬──────┬────────┬────────┐
│ user_id ┆ account_age_day ┆ total_transacti ┆ avg_amount_user ┆ … ┆ day ┆ hour ┆ minute ┆ second │
│ ---     ┆ s               ┆ ons_user        ┆ ---             ┆   ┆ --- ┆ ---  ┆ ---    ┆ ---    │
│ i16     ┆ ---             ┆ ---             ┆ f32             ┆   ┆ i8  ┆ i8   ┆ i8     ┆ i8     │
│         ┆ i16             ┆ i8              ┆                 ┆   ┆     ┆      ┆        ┆        │
╞═════════╪═════════════════╪═════════════════╪═════════════════╪═══╪═════╪══════╪════════╪════════╡
│ 1       ┆ 141             ┆ 47              ┆ 147.929993      ┆ … ┆ 6   ┆ 4    ┆ 9      ┆ 39     │
│ 1       ┆ 141             ┆ 47              ┆ 147.929993      ┆ … ┆ 9   ┆ 20   ┆ 13     ┆ 47     │
│ 1       ┆ 141             ┆ 47              ┆ 147.929993      ┆ … ┆ 12  ┆ 6    ┆ 20     ┆ 11     │
│ 1       ┆ 141             ┆ 47              ┆ 147.929993      ┆ … ┆ 15  ┆ 17   ┆ 0      ┆ 4      │
│ 1       ┆ 141             ┆ 47              ┆ 147.929993      ┆ … ┆ 17  ┆ 1    ┆ 27     ┆ 31     │
│ …       ┆ …               ┆ …               ┆ …               ┆ … ┆ …   ┆ …    ┆ …      ┆ …      │
│ 6000    ┆ 996             ┆ 45              ┆ 27.93           ┆ … ┆ 29  ┆ 4    ┆ 40     ┆ 54     │
│ 6000    ┆ 996             ┆ 45              ┆ 27.93           ┆ … ┆ 3   ┆ 8    ┆ 49     ┆ 2      │
│ 6000    ┆ 996             ┆ 45              ┆ 27.93           ┆ … ┆ 26  ┆ 7    ┆ 40     ┆ 38     │
│ 6000    ┆ 996             ┆ 45              ┆ 27.93           ┆ … ┆ 27  ┆ 9    ┆ 31     ┆ 56     │
│ 6000    ┆ 996             ┆ 45              ┆ 27.93           ┆ … ┆ 30  ┆ 11   ┆ 10     ┆ 23     │
└─────────┴─────────────────┴─────────────────┴─────────────────┴───┴─────┴──────┴────────┴────────┘

In [19]:
df = df.with_columns(
    pl.col('promo_used').cast(pl.Boolean),
    pl.col('avs_match').cast(pl.Boolean),
    pl.col('cvv_result').cast(pl.Boolean),
    pl.col('three_ds_flag').cast(pl.Boolean),
)

In [20]:
df.estimated_size('mb')

11.15524673461914

In [21]:
df

shape: (299_695, 21)
┌─────────┬─────────────────┬─────────────────┬─────────────────┬───┬─────┬──────┬────────┬────────┐
│ user_id ┆ account_age_day ┆ total_transacti ┆ avg_amount_user ┆ … ┆ day ┆ hour ┆ minute ┆ second │
│ ---     ┆ s               ┆ ons_user        ┆ ---             ┆   ┆ --- ┆ ---  ┆ ---    ┆ ---    │
│ i16     ┆ ---             ┆ ---             ┆ f32             ┆   ┆ i8  ┆ i8   ┆ i8     ┆ i8     │
│         ┆ i16             ┆ i8              ┆                 ┆   ┆     ┆      ┆        ┆        │
╞═════════╪═════════════════╪═════════════════╪═════════════════╪═══╪═════╪══════╪════════╪════════╡
│ 1       ┆ 141             ┆ 47              ┆ 147.929993      ┆ … ┆ 6   ┆ 4    ┆ 9      ┆ 39     │
│ 1       ┆ 141             ┆ 47              ┆ 147.929993      ┆ … ┆ 9   ┆ 20   ┆ 13     ┆ 47     │
│ 1       ┆ 141             ┆ 47              ┆ 147.929993      ┆ … ┆ 12  ┆ 6    ┆ 20     ┆ 11     │
│ 1       ┆ 141             ┆ 47              ┆ 147.929993      ┆ … ┆ 15  ┆ 17   ┆ 0      ┆ 4      │
│ 1       ┆ 141             ┆ 47              ┆ 147.929993      ┆ … ┆ 17  ┆ 1    ┆ 27     ┆ 31     │
│ …       ┆ …               ┆ …               ┆ …               ┆ … ┆ …   ┆ …    ┆ …      ┆ …      │
│ 6000    ┆ 996             ┆ 45              ┆ 27.93           ┆ … ┆ 29  ┆ 4    ┆ 40     ┆ 54     │
│ 6000    ┆ 996             ┆ 45              ┆ 27.93           ┆ … ┆ 3   ┆ 8    ┆ 49     ┆ 2      │
│ 6000    ┆ 996             ┆ 45              ┆ 27.93           ┆ … ┆ 26  ┆ 7    ┆ 40     ┆ 38     │
│ 6000    ┆ 996             ┆ 45              ┆ 27.93           ┆ … ┆ 27  ┆ 9    ┆ 31     ┆ 56     │
│ 6000    ┆ 996             ┆ 45              ┆ 27.93           ┆ … ┆ 30  ┆ 11   ┆ 10     ┆ 23     │
└─────────┴─────────────────┴─────────────────┴─────────────────┴───┴─────┴──────┴────────┴────────┘

In [22]:
X = df.select(
    cs.exclude('is_fraud')
)

In [23]:
y = df.get_column(
    'is_fraud'
)

In [24]:
X_numeric = df.select(
    cs.numeric()
)

In [25]:
X_categorical = df.select(
    cs.string()
)

In [26]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [27]:
column_transformer = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(
            handle_unknown='ignore', sparse_output=False, drop='first'),
        X_categorical.columns),
        ('pass', 'passthrough', X_numeric.columns)
    ]
)

In [28]:
column_transformer

ColumnTransformer(transformers=[('encoder',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['country', 'bin_country', 'channel',
                                  'merchant_category']),
                                ('pass', 'passthrough',
                                 ['user_id', 'account_age_days',
                                  'total_transactions_user', 'avg_amount_user',
                                  'amount', 'shipping_distance_km', 'year',
                                  'month', 'day', 'hour', 'minute',
                                  'second'])])

In [29]:
X_encoded = column_transformer.fit_transform(X)

In [30]:
feature_names = column_transformer.named_transformers_['encoder'].get_feature_names_out()

In [32]:
numeric_columns = df.select(cs.numeric()).columns

In [33]:
all_feature_names = list(feature_names) + list(numeric_columns)

In [36]:
X_encoded = pl.DataFrame(
    X_encoded, schema=all_feature_names
)

In [37]:
X_encoded

shape: (299_695, 35)
┌────────────┬────────────┬────────────┬────────────┬───┬──────┬──────┬────────┬────────┐
│ country_ES ┆ country_FR ┆ country_GB ┆ country_IT ┆ … ┆ day  ┆ hour ┆ minute ┆ second │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---  ┆ ---  ┆ ---    ┆ ---    │
│ f64        ┆ f64        ┆ f64        ┆ f64        ┆   ┆ f64  ┆ f64  ┆ f64    ┆ f64    │
╞════════════╪════════════╪════════════╪════════════╪═══╪══════╪══════╪════════╪════════╡
│ 0.0        ┆ 1.0        ┆ 0.0        ┆ 0.0        ┆ … ┆ 6.0  ┆ 4.0  ┆ 9.0    ┆ 39.0   │
│ 0.0        ┆ 1.0        ┆ 0.0        ┆ 0.0        ┆ … ┆ 9.0  ┆ 20.0 ┆ 13.0   ┆ 47.0   │
│ 0.0        ┆ 1.0        ┆ 0.0        ┆ 0.0        ┆ … ┆ 12.0 ┆ 6.0  ┆ 20.0   ┆ 11.0   │
│ 0.0        ┆ 1.0        ┆ 0.0        ┆ 0.0        ┆ … ┆ 15.0 ┆ 17.0 ┆ 0.0    ┆ 4.0    │
│ 0.0        ┆ 1.0        ┆ 0.0        ┆ 0.0        ┆ … ┆ 17.0 ┆ 1.0  ┆ 27.0   ┆ 31.0   │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …    ┆ …    ┆ …      ┆ …      │
│ 1.0        ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ … ┆ 29.0 ┆ 4.0  ┆ 40.0   ┆ 54.0   │
│ 1.0        ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ … ┆ 3.0  ┆ 8.0  ┆ 49.0   ┆ 2.0    │
│ 1.0        ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ … ┆ 26.0 ┆ 7.0  ┆ 40.0   ┆ 38.0   │
│ 1.0        ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ … ┆ 27.0 ┆ 9.0  ┆ 31.0   ┆ 56.0   │
│ 1.0        ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ … ┆ 30.0 ┆ 11.0 ┆ 10.0   ┆ 23.0   │
└────────────┴────────────┴────────────┴────────────┴───┴──────┴──────┴────────┴────────┘

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42
)